#!/usr/bin/env bash
# install.sh - install or switch ralphex executor between Kimi and Claude
#
# Usage:
#   ./install.sh kimi      # switch to Kimi CLI
#   ./install.sh original  # switch back to Claude Code

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
WRAPPER_SRC="$SCRIPT_DIR/kimi-as-claude.sh"

MODE="${1:-}"
if [[ "$MODE" != "kimi" && "$MODE" != "original" ]]; then
  echo "Usage: $0 <kimi|original>"
  echo ""
  echo "  kimi      - switch ralphex executor to Kimi CLI"
  echo "  original  - restore original Claude Code executor"
  exit 1
fi

# Detect target project (current directory)
TARGET_DIR="$(pwd)"
RALPHEX_DIR="$TARGET_DIR/.ralphex"
SCRIPTS_DIR="$RALPHEX_DIR/scripts"
CONFIG_FILE="$RALPHEX_DIR/config"
BACKUP_FILE="$RALPHEX_DIR/config.backup"
SENTINEL_FILE="$RALPHEX_DIR/.kimi-no-original-config"
WRAPPER_DST="$SCRIPTS_DIR/kimi-as-claude.sh"
REL_WRAPPER=".ralphex/scripts/kimi-as-claude.sh"

# Ensure .ralphex/ exists (create if missing)
mkdir -p "$RALPHEX_DIR"

if [[ "$MODE" == "kimi" ]]; then
  echo "[ralphex-kimi] Switching to Kimi CLI executor..."

  # verify wrapper source exists
  if [[ ! -f "$WRAPPER_SRC" ]]; then
    echo "error: wrapper script not found at $WRAPPER_SRC"
    exit 1
  fi

  # create scripts directory
  mkdir -p "$SCRIPTS_DIR"

  # copy wrapper
  cp "$WRAPPER_SRC" "$WRAPPER_DST"
  chmod +x "$WRAPPER_DST"
  echo "[ralphex-kimi] Wrapper installed to $WRAPPER_DST"

  # backup existing config (only if original config existed and no backup yet)
  # sentinel means "no original config existed"; skip backup creation in that case
  if [[ ! -f "$BACKUP_FILE" && ! -f "$SENTINEL_FILE" ]]; then
    if [[ -f "$CONFIG_FILE" ]]; then
      cp "$CONFIG_FILE" "$BACKUP_FILE"
      echo "[ralphex-kimi] Config backed up to $BACKUP_FILE"
    else
      # create a sentinel file so restore knows there was no original config
      touch "$SENTINEL_FILE"
      echo "[ralphex-kimi] No original config found; sentinel created."
    fi
  fi

  # update or create config
  if [[ -f "$CONFIG_FILE" ]]; then
    TMP_CONFIG="$(mktemp)"
    has_claude_command=0
    has_claude_args=0

    while IFS= read -r line || [[ -n "$line" ]]; do
      if [[ "$line" =~ ^#?[[:space:]]*claude_command[[:space:]]*= ]]; then
        echo "claude_command = $REL_WRAPPER" >> "$TMP_CONFIG"
        has_claude_command=1
      elif [[ "$line" =~ ^#?[[:space:]]*claude_args[[:space:]]*= ]]; then
        echo "claude_args =" >> "$TMP_CONFIG"
        has_claude_args=1
      else
        echo "$line" >> "$TMP_CONFIG"
      fi
    done < "$CONFIG_FILE"

    # append missing keys at the end
    if [[ "$has_claude_command" -eq 0 ]]; then
      echo "" >> "$TMP_CONFIG"
      echo "# Kimi executor (added by ralphex-kimi)" >> "$TMP_CONFIG"
      echo "claude_command = $REL_WRAPPER" >> "$TMP_CONFIG"
    fi
    if [[ "$has_claude_args" -eq 0 ]]; then
      echo "claude_args =" >> "$TMP_CONFIG"
    fi

    mv "$TMP_CONFIG" "$CONFIG_FILE"
  else
    # create minimal config
    cat > "$CONFIG_FILE" <<EOF
# Kimi executor (added by ralphex-kimi)
claude_command = $REL_WRAPPER
claude_args =
EOF
  fi

  echo "[ralphex-kimi] Config updated: claude_command → $WRAPPER_DST"
  echo "[ralphex-kimi] Done. Run 'ralphex docs/plans/your-plan.md' to use Kimi."

else
  echo "[ralphex-kimi] Restoring original Claude Code executor..."

  if [[ -f "$BACKUP_FILE" ]]; then
    # restore from backup and clean up sentinel if present
    mv "$BACKUP_FILE" "$CONFIG_FILE"
    rm -f "$SENTINEL_FILE"
    echo "[ralphex-kimi] Config restored from backup."
  elif [[ -f "$SENTINEL_FILE" ]]; then
    # no original config existed; remove only Kimi keys from config
    if [[ -f "$CONFIG_FILE" ]]; then
      TMP_CONFIG="$(mktemp)"
      has_content=0
      while IFS= read -r line || [[ -n "$line" ]]; do
        if [[ "$line" =~ ^#?[[:space:]]*claude_command[[:space:]]*= ]] || \
           [[ "$line" =~ ^#?[[:space:]]*claude_args[[:space:]]*= ]]; then
          # skip Kimi keys
          continue
        elif [[ "$line" =~ ^#.*Kimi.executor.*added.by.ralphex-kimi ]]; then
          # skip our comment header
          continue
        elif [[ -n "${line// /}" ]]; then
          has_content=1
          echo "$line" >> "$TMP_CONFIG"
        else
          echo "$line" >> "$TMP_CONFIG"
        fi
      done < "$CONFIG_FILE"

      if [[ "$has_content" -eq 0 ]]; then
        # config became empty after removing Kimi keys
        rm -f "$CONFIG_FILE"
        echo "[ralphex-kimi] Config was generated by installer and is now empty; removed."
      else
        mv "$TMP_CONFIG" "$CONFIG_FILE"
        echo "[ralphex-kimi] Kimi keys removed from config; user settings preserved."
      fi
    fi
    rm -f "$SENTINEL_FILE"
  else
    # no backup and no sentinel — do NOT delete user's config
    echo "error: no backup or sentinel found. Cannot safely restore config." >&2
    echo "       If you want to switch back to Claude Code, manually edit $CONFIG_FILE" >&2
    exit 1
  fi

  if [[ -f "$WRAPPER_DST" ]]; then
    rm -f "$WRAPPER_DST"
    echo "[ralphex-kimi] Wrapper removed."
  fi

  echo "[ralphex-kimi] Done. Claude Code is restored as the default executor."
fi
